server:
   port: 8100
spring:
   application:
      name: base-job
mybatis:
   config-location: classpath:mybatis-config.xml
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.eagle.micro.model.job