server:
  port: 9001

spring:
  cloud:
    refresh:
      refreshable: none # 这个配置因为springboot循环依赖bug

app:
  kafka:
    servers: 127.0.0.1:9092
    group-id: fink-demo
    index-source-topic:
      - fink-index-source
    index-sink-topic:
      - fink-index-sink
