eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      version: release
      
server:
  port: 9000
  
spring:
  cloud:
    refresh:
      refreshable: none # 这个配置因为springboot循环依赖bug
  datasource:
    url: jdbc:h2:mem:demo
    username: admin
    password:
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none